config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'home#index'
  get 'home/team'
  post 'home/team'
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  before_action :get_name, only: [:index]


  def get_name
    @prefix = Faker::Superhero.prefix
    @name = Faker::Superhero.name
    @power = Faker::Superhero.power
    @corp_title = Faker::Job.title
    @corp_power = Faker::Company.bs.titleize 
    @rand_num = rand(1..100)
    @set_num = rand(1..4)
    @bg_num = rand(1..2)
    @avatar = Faker::Avatar.image(slug: @rand_num, size: "300x300", format: "png", set: "set#{@set_num}", bgset: "bg#{@bg_num}")
  end

  def index
  end

  def team
    @team_size = params[:team_size]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true
module HomeHelper
end

app/views/home/_form.html.erb
<div class='row'>
  <div class='col-md-4'>
    <%= form_tag home_team_path, method: :post do %>
      <%= select_tag :team_size, options_for_select([
        ['1', 1],
        ['2', 2], 
        ['3', 3], 
        ['4', 4], 
        ['5', 5], 
        ['6', 6], 
        ['7', 7], 
        ['8', 8], 
        ['9', 9], 
        ['10', 10] 
      ]), class: 'form-control' %>
      <br/></br>
      <%= submit_tag 'Build your team', class: 'btn btn-default'  %>
    <% end %>
  </div>
  <div class='col-md-4'>
  </div>
  <div class='col-md-4'>
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5" >
  <%= link_to 'SUPERHERO NAME GENERATOR', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
				<%= link_to "Home", root_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
				<%= link_to "Create team", home_team_path, class: 'nav-link'%>
      </li>
    </ul>
  </div>
</nav>

app/views/home/_show_team.html.erb
<% @team_size.to_i.times do %>
    <div class='row my-2'>
      <div class='col-md-4'>
        <%= image_tag Faker::Avatar.image(slug: rand(1..100), size: "300x300", format: "png", set: "set#{rand(1..4)}", bgset: "bg#{rand(1..2)}")  %>
      </div>
      <div class='col-md-4'>
        <h3>
          Name:<br />
          <span class='red'><%= Faker::Superhero.prefix + ' ' + Faker::Superhero.name %></span> <br />
        </h3>
        <h3>
          Power:<br /> 
          <span class='red'><%= Faker::Superhero.power %></span><br /><br />
        </h3>
        <h4>
          Undercover Day Job Is: <br />
          <span class='red'><%= Faker::Job.title %><span> <br />
        </h4>
        <h4>
          Coporate Superpower: <br />
          <span class='red'><%= Faker::Company.bs.titleize %></span>
        </h4>
      </div>
    </div>
    <div class='row'>
      <hr>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="card">
  <div class="card-header gray">
    <%= link_to 'Click Here To Generate A New Superhero', root_path %>
  </div>
  <div class="card-body">
    <div class='row my-2'>
      <div class='col-md-4'>
        <%= image_tag @avatar %>
      </div>
      <div class='col-md-4'>
        <h3>
          Name:<br />
          <span class='red'><%= @prefix + ' ' + @name %></span> <br />
        </h3>
        <h3>
          Power:<br /> 
          <span class='red'><%= @power %></span><br /><br />
        </h3>
        <h4>
          Undercover Day Job Is: <br />
          <span class='red'><%= @corp_title %><span> <br />
        </h4>
        <h4>
          Coporate Superpower: <br />
          <span class='red'><%= @corp_power%></span>
        </h4>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Create A Whole Superhero Team', home_team_path %>
  </div>
</div>

app/views/home/team.html.erb
<div class="card">
  <div class="card-header gray">
    <%= @team_size ? "Here's your team" : "How many team members do you want?" %>
  </div>
  <div class="card-body">
    <% if @team_size %>
      <%= render 'show_team' %>
    <% else %>
      <%= render 'form' %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Create A Whole Superhero Team', home_team_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'home/navbar'  %>
     <div class="container"> 
       <%= yield %> 
     </div>
  </body>
</html>